[project]
name = "ad-api"
version = "0.1.0"
description = "API em FASTAPI para executar ações em Active Directory"
readme = "README.md"
authors = [
    { name = "Victor Alexandre B Milhomem", email = "valex.milhomem@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "ldap3>=2.9.1",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
ad-api = "ad_api:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-env>=1.7.1",
]

[tool.pytest.ini_options]
env_files = [".env.test"]
